
package com.kevapp.webservice.serverws.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISong", targetNamespace = "http://service.serverws.webservice.kevapp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISong {


    /**
     * 
     * @return
     *     returns java.util.List<com.kevapp.webservice.serverws.service.Song>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSongs", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.GetAllSongs")
    @ResponseWrapper(localName = "getAllSongsResponse", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.GetAllSongsResponse")
    @Action(input = "http://service.serverws.webservice.kevapp.com/ISong/getAllSongsRequest", output = "http://service.serverws.webservice.kevapp.com/ISong/getAllSongsResponse")
    public List<Song> getAllSongs();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.kevapp.webservice.serverws.service.Song
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSong", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.GetSong")
    @ResponseWrapper(localName = "getSongResponse", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.GetSongResponse")
    @Action(input = "http://service.serverws.webservice.kevapp.com/ISong/getSongRequest", output = "http://service.serverws.webservice.kevapp.com/ISong/getSongResponse")
    public Song getSong(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSong", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.CreateSong")
    @ResponseWrapper(localName = "createSongResponse", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.CreateSongResponse")
    @Action(input = "http://service.serverws.webservice.kevapp.com/ISong/createSongRequest", output = "http://service.serverws.webservice.kevapp.com/ISong/createSongResponse")
    public boolean createSong(
        @WebParam(name = "arg0", targetNamespace = "")
        Song arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSong", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.UpdateSong")
    @ResponseWrapper(localName = "updateSongResponse", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.UpdateSongResponse")
    @Action(input = "http://service.serverws.webservice.kevapp.com/ISong/updateSongRequest", output = "http://service.serverws.webservice.kevapp.com/ISong/updateSongResponse")
    public boolean updateSong(
        @WebParam(name = "arg0", targetNamespace = "")
        Song arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeSong", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.RemoveSong")
    @ResponseWrapper(localName = "removeSongResponse", targetNamespace = "http://service.serverws.webservice.kevapp.com/", className = "com.kevapp.webservice.serverws.service.RemoveSongResponse")
    @Action(input = "http://service.serverws.webservice.kevapp.com/ISong/removeSongRequest", output = "http://service.serverws.webservice.kevapp.com/ISong/removeSongResponse")
    public boolean removeSong(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
